version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306" # Expose MySQL port
    networks:
      - mysql_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  mysql_network:
    driver: bridge
