version: '3.8'

services:
  backend:
    build:
      context: ./Backend/init
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:80"
    networks:
      - project_network
    depends_on:
      - mysql

  frontend:
    build:
      context: ./Frontend/init
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - project_network
    depends_on:
      - backend

  mysql:
    build:
      context: ./Database/init
      dockerfile: Dockerfile
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - project_network

networks:
  project_network:
    driver: bridge
