
services:
  backend:
    build:
      context: ./Backend/init
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:80"
    networks:
      - project_network
    depends_on:
      - mysql
    volumes:
      - ./Backend/src:/var/www/html
      #- ./.env:/var/www/html/.env:ro
#      - ./Backend/docs:/var/www/html/docs
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    env_file:
      - .env

  frontend:
    build:
      context: ./Frontend/init
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - project_network
    depends_on:
      - backend
    volumes:
      - ./Frontend/src:/var/www/html

  mysql:
    build:
      context: ./Database/init
      dockerfile: Dockerfile
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - project_network
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    env_file:
      - .env

networks:
  project_network:
    driver: bridge
