version: '3.8'

services:
  mysql:
    build:
      context: Database/.docker
      dockerfile: Dockerfile
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - project_network
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  webapp:
    build:
      context: ./WebApp
      dockerfile: .docker/Dockerfile
    container_name: webapp
    ports:
      - "8080:80"
    networks:
      - project_network
    volumes:
      - ./WebApp:/var/www/html
      - ./WebApp/logs:/var/www/html/logs
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_PORT=${SMTP_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - API_TOKEN=${API_TOKEN}
      - URL=${URL}
    env_file:
      - .env

networks:
  project_network:
    driver: bridge

volumes:
  db_data:
