openapi: 3.0.0
info:
  title: Feedback System API
  description: API for managing authentication, users, messages, and courses.
  version: 1.0.0
servers:
  - url: http://158.39.188.204/steg1/api
    description: Local development server

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                role:
                  type: string
                  enum: [ student, lecturer, admin ]
      responses:
        200:
          description: Registration successful
        400:
          description: Validation error
  /auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        200:
          description: Login successful
        401:
          description: Unauthorized
  
  /auth/logout:
  /auth/change-password:
  /auth/password-reset/request:
  /auth/reset-password:

  /student/courses:
  /student/messages:
  /student/message/send:

  /lecturer/courses:
  /lecturer/messages:
  /lecturer/message/reply:
  /lecturer/message/resolve:

  /admin/users:
  /admin/user/delete:
  /admin/messages/reported:
  /admin/message/delete:
  /admin/message/update:
  /admin/user/details:

  /guest/messages:
  /guest/messages/view:
  /guest/messages/report:
  /guest/messages/comment:

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
